spring.application.name=email-service
# 1. La porta del microservizio
server.port=8083

# 2. Il Server di posta (Usiamo Gmail come esempio)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alfonso.lombardi98@gmail.com
spring.mail.password=ubqjururzxipufxq

# Regole di sicurezza fisse di Spring
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true