spring.application.name=booking-service
server.port=8082

# Connessione al database (Nota la porta 5433 e il nome booking_db)
spring.datasource.url=jdbc:postgresql://localhost:5433/booking_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true